; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\aMotoo\Documents\MyProject\WordDicBT\WDDatas\AssemblyInfo.cpp"
