; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\aMotoo\Documents\MyProject\WordDicBT\WDDatas\Stdafx.cpp"
.global	__@@_PchSym_@00@UfhvihUznlgllUwlxfnvmghUnbkilqvxgUdliwwrxygUdwwzgzhUwvyftUhgwzucOlyq@
.local	__@@_PchSym_@00@UfhvihUznlgllUwlxfnvmghUnbkilqvxgUdliwwrxygUdwwzgzhUwvyftUhgwzucOlyq@,4
