; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\aMotoo\Documents\MyProject\WordDicBT\WDDatas\WDDatasException.cpp"
.global	?ErrorCode2@WDDatasException@WDDatas@@3HA	; WDDatas::WDDatasException::ErrorCode2
.global	?ErrorCode@WDDatasException@WDDatas@@3HA	; WDDatas::WDDatasException::ErrorCode
.global	
	.bss
.local	?ErrorCode2@WDDatasException@WDDatas@@3HA,4	; WDDatas::WDDatasException::ErrorCode2
.local	?ErrorCode@WDDatasException@WDDatas@@3HA,4	; WDDatas::WDDatasException::ErrorCode
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ??0WDDatasException@WDDatas@@$$FQ$AAM@XZ
.global	??0WDDatasException@WDDatas@@$$FQ$AAM@XZ	; WDDatas::WDDatasException::WDDatasException
??0WDDatasException@WDDatas@@$$FQ$AAM@XZ:		; WDDatas::WDDatasException::WDDatasException
;	.proc.def	D:V()

; Function Header:
; max stack depth = 2
; function size = 21 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4E3AA1).class (token:0x4E3AA3)

;	.proc.beg
; File c:\users\amotoo\documents\myproject\worddicbt\wddatas\wddatasexception.cpp
; Line 19
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
	ldarg.0				; this$
	call		??0Exception@System@@$$FQ$AAM@XZ
; Line 20
	ret		
 .end ??0WDDatasException@WDDatas@@$$FQ$AAM@XZ		; WDDatas::WDDatasException::WDDatasException
;	.proc.end.void
.global	
	.bss
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
.global	??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z ; WDDatas::WDDatasException::WDDatasException
??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z: ; WDDatas::WDDatasException::WDDatasException
;	.proc.def	D:V(P)

; Function Header:
; max stack depth = 2
; function size = 22 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 1,"msg$" SIG: string
;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4E3AA1).class (token:0x4E3AA3)

;	.proc.beg
; Line 25
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
	ldarg.0				; this$
	ldarg.1				; msg$
	call		??0Exception@System@@$$FQ$AAM@P$AAVString@1@@Z
; Line 26
	ret		
 .end ??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z ; WDDatas::WDDatasException::WDDatasException
;	.proc.end.void
.global	
	.bss
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
.global	??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z ; WDDatas::WDDatasException::WDDatasException
??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z: ; WDDatas::WDDatasException::WDDatasException
;	.proc.def	D:V(PP)

; Function Header:
; max stack depth = 3
; function size = 23 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 2,"inner$" SIG: class (token:0x4E3915)
;	.formal.mptr 1,"msg$" SIG: string
;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4E3AA1).class (token:0x4E3AA3)

;	.proc.beg
; Line 31
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
	ldarg.0				; this$
	ldarg.1				; msg$
	ldarg.2				; inner$
	call		??0Exception@System@@$$FQ$AAM@P$AAVString@1@P$AAV01@@Z
; Line 32
	ret		
 .end ??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z ; WDDatas::WDDatasException::WDDatasException
;	.proc.end.void
