; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\aMotoo\Documents\MyProject\WordDicBT\WDDatas\WDTrans.cpp"
.global	
	.bss
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	any, ??0WDRec@WDDatas@@$$FQ$AAM@XZ
.global	??0WDRec@WDDatas@@$$FQ$AAM@XZ			; WDDatas::WDRec::WDRec
??0WDRec@WDDatas@@$$FQ$AAM@XZ:				; WDDatas::WDRec::WDRec
;	.proc.def	D:V()

; Function Header:
; max stack depth = 1
; function size = 7 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED7E9).class (token:0x4ED7EB)

;	.proc.beg
	ldarg.0				; this$
	call		??0Object@System@@$$FQ$AAM@XZ
	ret		
 .end ??0WDRec@WDDatas@@$$FQ$AAM@XZ			; WDDatas::WDRec::WDRec
;	.proc.end.void
; Function compile flags: /Ogtp
	.text
	.comdat	any, ?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
.global	?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z		; WDDatas::WDRec::<Dispose>
?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z:		; WDDatas::WDRec::<Dispose>
;	.proc.def	D:V(I)

; Function Header:
; max stack depth = 1
; function size = 18 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED7E9).class (token:0x4ED7EB)
;	.formal.u1 1,"disposing$" SIG: bool

;	.proc.beg
	ldarg.1				; disposing$
	brfalse.s	$LN2@
	ldarg.0				; this$
	call		??1WDRec@WDDatas@@$$FA$AAM@XZ
	br.s		$LN1@
$LN2@:
	ldarg.0				; this$
	call		?<Finalize>@Object@System@@$$FM$AAMXXZ
$LN1@:
	ret		
 .end ?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z		; WDDatas::WDRec::<Dispose>
;	.proc.end.void
.global	
	.bss
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	any, ?<Dispose>@WDWord@WDDatas@@$$FM$AAMX_N@Z
.global	?<Dispose>@WDWord@WDDatas@@$$FM$AAMX_N@Z	; WDDatas::WDWord::<Dispose>
?<Dispose>@WDWord@WDDatas@@$$FM$AAMX_N@Z:		; WDDatas::WDWord::<Dispose>
;	.proc.def	D:V(I)

; Function Header:
; max stack depth = 2
; function size = 27 bytes
; local varsig tk = 0x0 
; Exception Information:
; 1 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED3E9).class (token:0x4ED3EB)
;	.formal.u1 1,"disposing$" SIG: bool

;	.proc.beg
	ldarg.1				; disposing$
	brfalse.s	$LN3@
$LN13@:
	ldarg.0				; this$
	call		??1WDWord@WDDatas@@$$FA$AAM@XZ
$LN2@:
	leave.s		$LN12@
$LN7@:
	ldarg.0				; this$
	ldc.i.1		1		; u8 0x1
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN9@:
	endfinally	
$LN3@:
	ldarg.0				; this$
	ldc.i.0		0		; u8 0x0
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN12@:
	ret		
 .end ?<Dispose>@WDWord@WDDatas@@$$FM$AAMX_N@Z		; WDDatas::WDWord::<Dispose>
;	.proc.end.void
.global	
	.bss
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	any, ??0WDMeanGroup@WDDatas@@$$FQ$AAM@XZ
.global	??0WDMeanGroup@WDDatas@@$$FQ$AAM@XZ		; WDDatas::WDMeanGroup::WDMeanGroup
??0WDMeanGroup@WDDatas@@$$FQ$AAM@XZ:			; WDDatas::WDMeanGroup::WDMeanGroup
;	.proc.def	D:V()

; Function Header:
; max stack depth = 1
; function size = 7 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED359).class (token:0x4ED35B)

;	.proc.beg
	ldarg.0				; this$
	call		??0Object@System@@$$FQ$AAM@XZ
	ret		
 .end ??0WDMeanGroup@WDDatas@@$$FQ$AAM@XZ		; WDDatas::WDMeanGroup::WDMeanGroup
;	.proc.end.void
.global	
	.bss
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	any, ??0WDMeanGrpComparer@WDDatas@@$$FQ$AAM@XZ
.global	??0WDMeanGrpComparer@WDDatas@@$$FQ$AAM@XZ	; WDDatas::WDMeanGrpComparer::WDMeanGrpComparer
??0WDMeanGrpComparer@WDDatas@@$$FQ$AAM@XZ:		; WDDatas::WDMeanGrpComparer::WDMeanGrpComparer
;	.proc.def	D:V()

; Function Header:
; max stack depth = 1
; function size = 7 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED2C1).class (token:0x4ED2C3)

;	.proc.beg
	ldarg.0				; this$
	call		??0Object@System@@$$FQ$AAM@XZ
	ret		
 .end ??0WDMeanGrpComparer@WDDatas@@$$FQ$AAM@XZ		; WDDatas::WDMeanGrpComparer::WDMeanGrpComparer
;	.proc.end.void
.global	
	.bss
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	any, ?<Dispose>@WDMean@WDDatas@@$$FM$AAMX_N@Z
.global	?<Dispose>@WDMean@WDDatas@@$$FM$AAMX_N@Z	; WDDatas::WDMean::<Dispose>
?<Dispose>@WDMean@WDDatas@@$$FM$AAMX_N@Z:		; WDDatas::WDMean::<Dispose>
;	.proc.def	D:V(I)

; Function Header:
; max stack depth = 2
; function size = 27 bytes
; local varsig tk = 0x0 
; Exception Information:
; 1 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED17D).class (token:0x4ED17F)
;	.formal.u1 1,"disposing$" SIG: bool

;	.proc.beg
	ldarg.1				; disposing$
	brfalse.s	$LN3@
$LN13@:
	ldarg.0				; this$
	call		??1WDMean@WDDatas@@$$FA$AAM@XZ
$LN2@:
	leave.s		$LN12@
$LN7@:
	ldarg.0				; this$
	ldc.i.1		1		; u8 0x1
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN9@:
	endfinally	
$LN3@:
	ldarg.0				; this$
	ldc.i.0		0		; u8 0x0
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN12@:
	ret		
 .end ?<Dispose>@WDMean@WDDatas@@$$FM$AAMX_N@Z		; WDDatas::WDMean::<Dispose>
;	.proc.end.void
.global	?WDMeanGrpComp@WDMean@WDDatas@@0P$AAVWDMeanGrpComparer@2@$AA ; WDDatas::WDMean::WDMeanGrpComp
	.bss
.local	?WDMeanGrpComp@WDMean@WDDatas@@0P$AAVWDMeanGrpComparer@2@$AA,4 ; WDDatas::WDMean::WDMeanGrpComp
; Function compile flags: /Ogtp
	.text
	.comdat	any, ?.cctor@WDMean@WDDatas@@$$FSMXXZ
.global	?.cctor@WDMean@WDDatas@@$$FSMXXZ		; ?.cctor@WDMean@WDDatas@@$$FSMXXZ
?.cctor@WDMean@WDDatas@@$$FSMXXZ:			; ?.cctor@WDMean@WDDatas@@$$FSMXXZ
;	.proc.def	D:V()

; Function Header:
; max stack depth = 1
; function size = 7 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers


;	.proc.beg
	ldnull		0		; i32 0x0
	stsfld		?WDMeanGrpComp@WDMean@WDDatas@@0P$AAVWDMeanGrpComparer@2@$AA
	ret		
 .end ?.cctor@WDMean@WDDatas@@$$FSMXXZ			; ?.cctor@WDMean@WDDatas@@$$FSMXXZ
;	.proc.end.void
.global	
	.bss
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	any, ?<Dispose>@WDRelation@WDDatas@@$$FM$AAMX_N@Z
.global	?<Dispose>@WDRelation@WDDatas@@$$FM$AAMX_N@Z	; WDDatas::WDRelation::<Dispose>
?<Dispose>@WDRelation@WDDatas@@$$FM$AAMX_N@Z:		; WDDatas::WDRelation::<Dispose>
;	.proc.def	D:V(I)

; Function Header:
; max stack depth = 2
; function size = 27 bytes
; local varsig tk = 0x0 
; Exception Information:
; 1 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ECEF9).class (token:0x4ECEFB)
;	.formal.u1 1,"disposing$" SIG: bool

;	.proc.beg
	ldarg.1				; disposing$
	brfalse.s	$LN3@
$LN13@:
	ldarg.0				; this$
	call		??1WDRelation@WDDatas@@$$FA$AAM@XZ
$LN2@:
	leave.s		$LN12@
$LN7@:
	ldarg.0				; this$
	ldc.i.1		1		; u8 0x1
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN9@:
	endfinally	
$LN3@:
	ldarg.0				; this$
	ldc.i.0		0		; u8 0x0
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN12@:
	ret		
 .end ?<Dispose>@WDRelation@WDDatas@@$$FM$AAMX_N@Z	; WDDatas::WDRelation::<Dispose>
;	.proc.end.void
.global	
	.bss
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	any, ?<Dispose>@WDGroup@WDDatas@@$$FM$AAMX_N@Z
.global	?<Dispose>@WDGroup@WDDatas@@$$FM$AAMX_N@Z	; WDDatas::WDGroup::<Dispose>
?<Dispose>@WDGroup@WDDatas@@$$FM$AAMX_N@Z:		; WDDatas::WDGroup::<Dispose>
;	.proc.def	D:V(I)

; Function Header:
; max stack depth = 2
; function size = 27 bytes
; local varsig tk = 0x0 
; Exception Information:
; 1 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ECDB5).class (token:0x4ECDB7)
;	.formal.u1 1,"disposing$" SIG: bool

;	.proc.beg
	ldarg.1				; disposing$
	brfalse.s	$LN3@
$LN13@:
	ldarg.0				; this$
	call		??1WDGroup@WDDatas@@$$FA$AAM@XZ
$LN2@:
	leave.s		$LN12@
$LN7@:
	ldarg.0				; this$
	ldc.i.1		1		; u8 0x1
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN9@:
	endfinally	
$LN3@:
	ldarg.0				; this$
	ldc.i.0		0		; u8 0x0
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN12@:
	ret		
 .end ?<Dispose>@WDGroup@WDDatas@@$$FM$AAMX_N@Z		; WDDatas::WDGroup::<Dispose>
;	.proc.end.void
.global	
	.bss
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	any, ?<Dispose>@WDSegment@WDDatas@@$$FM$AAMX_N@Z
.global	?<Dispose>@WDSegment@WDDatas@@$$FM$AAMX_N@Z	; WDDatas::WDSegment::<Dispose>
?<Dispose>@WDSegment@WDDatas@@$$FM$AAMX_N@Z:		; WDDatas::WDSegment::<Dispose>
;	.proc.def	D:V(I)

; Function Header:
; max stack depth = 2
; function size = 27 bytes
; local varsig tk = 0x0 
; Exception Information:
; 1 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ECC69).class (token:0x4ECC6B)
;	.formal.u1 1,"disposing$" SIG: bool

;	.proc.beg
	ldarg.1				; disposing$
	brfalse.s	$LN3@
$LN13@:
	ldarg.0				; this$
	call		??1WDSegment@WDDatas@@$$FA$AAM@XZ
$LN2@:
	leave.s		$LN12@
$LN7@:
	ldarg.0				; this$
	ldc.i.1		1		; u8 0x1
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN9@:
	endfinally	
$LN3@:
	ldarg.0				; this$
	ldc.i.0		0		; u8 0x0
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN12@:
	ret		
 .end ?<Dispose>@WDSegment@WDDatas@@$$FM$AAMX_N@Z	; WDDatas::WDSegment::<Dispose>
;	.proc.end.void
.global	?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA ; WDDatas::WDTrans::TransNo
.global	?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA ; WDDatas::WDTrans::TransID
.global	?MeanNo@WDTrans@WDDatas@@3HA			; WDDatas::WDTrans::MeanNo
.global	?WordID@WDTrans@WDDatas@@3HA			; WDDatas::WDTrans::WordID
.global	
	.bss
.local	?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA,4 ; WDDatas::WDTrans::TransNo
.local	?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA,4 ; WDDatas::WDTrans::TransID
.local	?MeanNo@WDTrans@WDDatas@@3HA,4			; WDDatas::WDTrans::MeanNo
.local	?WordID@WDTrans@WDDatas@@3HA,4			; WDDatas::WDTrans::WordID
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ??0WDTrans@WDDatas@@$$FQ$AAM@XZ
.global	??0WDTrans@WDDatas@@$$FQ$AAM@XZ			; WDDatas::WDTrans::WDTrans
??0WDTrans@WDDatas@@$$FQ$AAM@XZ:			; WDDatas::WDTrans::WDTrans
;	.proc.def	D:V()

; Function Header:
; max stack depth = 2
; function size = 53 bytes
; local varsig tk = 0x0 
; Exception Information:
; 1 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)

;	.proc.beg
; File c:\users\amotoo\documents\myproject\worddicbt\wddatas\wdtrans.cpp
; Line 24
	ldarg.0				; this$
	call		??0Object@System@@$$FQ$AAM@XZ
$LN6@WDTrans:
; Line 26
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?WordID@WDTrans@WDDatas@@3HA
; Line 27
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?MeanNo@WDTrans@WDDatas@@3HA
; Line 29
	ldarg.0				; this$
	newobj		??0?$List@H@Generic@Collections@System@@$$FQ$AAM@XZ
	stfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
; Line 30
	ldarg.0				; this$
	newobj		??0?$List@H@Generic@Collections@System@@$$FQ$AAM@XZ
	stfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	leave.s		$LN7@WDTrans
$LN8@WDTrans:
	ldarg.0				; this$
	ldc.i.1		1		; u8 0x1
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
	endfinally	
$LN7@WDTrans:
; Line 31
	ret		
 .end ??0WDTrans@WDDatas@@$$FQ$AAM@XZ			; WDDatas::WDTrans::WDTrans
;	.proc.end.void
	.bss
.local	$T12610,0
.local	$TypeTok$1102D1B0$,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ??1WDTrans@WDDatas@@$$FA$AAM@XZ
.global	??1WDTrans@WDDatas@@$$FA$AAM@XZ			; WDDatas::WDTrans::~WDTrans
??1WDTrans@WDDatas@@$$FA$AAM@XZ:			; WDDatas::WDTrans::~WDTrans
;	.proc.def	D:V()

; Function Header:
; max stack depth = 1
; function size = 53 bytes
; local varsig tk = 0x1100000A 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.mptr 0,"$T11971" SIG: class (token:0x4F0CF5)
;	.local.u4 1,"$T12609" SIG: genericInst (token:0x100000E) <i4>
;	.local.mptr 2,"$T11965" SIG: class (token:0x4F0CF5)
;	.local.u4 3,"$T12608" SIG: genericInst (token:0x100000E) <i4>

;	.proc.beg
; Line 76
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.3				; $T12608
	ldloc.3				; $T12608
	brfalse.s	$LN5@WDTrans@2
	ldloc.3				; $T12608
	isInst		$TypeTok$1102D1B0$
	stloc.2				; $T11965
	ldloc.2				; $T11965
	brfalse.s	$LN5@WDTrans@2
	ldloc.2				; $T11965
	callvirt	?<Dispose>@IDisposable@System@@$$FU$AAMXXZ
$LN5@WDTrans@2:
; Line 77
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.1				; $T12609
	ldloc.1				; $T12609
	brfalse.s	$LN7@WDTrans@2
	ldloc.1				; $T12609
	isInst		$TypeTok$1102D1B0$
	stloc.0				; $T11971
	ldloc.0				; $T11971
	brfalse.s	$LN7@WDTrans@2
	ldloc.0				; $T11971
	callvirt	?<Dispose>@IDisposable@System@@$$FU$AAMXXZ
$LN7@WDTrans@2:
; Line 78
	ret		
 .end ??1WDTrans@WDDatas@@$$FA$AAM@XZ			; WDDatas::WDTrans::~WDTrans
;	.proc.end.void
	.bss
.local	$T12614,0
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?DataLength@WDTrans@WDDatas@@$$FQ$AAMHXZ
.global	?DataLength@WDTrans@WDDatas@@$$FQ$AAMHXZ	; WDDatas::WDTrans::DataLength
?DataLength@WDTrans@WDDatas@@$$FQ$AAMHXZ:		; WDDatas::WDTrans::DataLength
;	.proc.def	D:I()

; Function Header:
; max stack depth = 3
; function size = 25 bytes
; local varsig tk = 0x1100000B 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.u4 0,"$T12613" SIG: genericInst (token:0x100000E) <i4>

;	.proc.beg
; Line 284
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.0				; $T12613
	ldloc.0				; $T12613
	brtrue.s	$LN2@DataLength
; Line 286
	ldc.i.0		0		; i32 0x0
; Line 287
	br.s		$LN1@DataLength
$LN2@DataLength:
; Line 288
	ldloc.0				; $T12613
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	ldc.i.3		3		; i32 0x3
	shl		
$LN1@DataLength:
; Line 294
	ldc.i4.s	12		; i32 0xc
	add		
	ret		
 .end ?DataLength@WDTrans@WDDatas@@$$FQ$AAMHXZ		; WDDatas::WDTrans::DataLength
;	.proc.end.i4
	.bss
.local	$T12624,0
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?RecLength@WDTrans@WDDatas@@$$FU$AAMHXZ
.global	?RecLength@WDTrans@WDDatas@@$$FU$AAMHXZ		; WDDatas::WDTrans::RecLength
?RecLength@WDTrans@WDDatas@@$$FU$AAMHXZ:		; WDDatas::WDTrans::RecLength
;	.proc.def	D:I()

; Function Header:
; max stack depth = 3
; function size = 31 bytes
; local varsig tk = 0x1100000B 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.u4 0,"$T12623" SIG: genericInst (token:0x100000E) <i4>

;	.proc.beg
; Line 300
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.0				; $T12623
	ldloc.0				; $T12623
	brtrue.s	$LN4@RecLength
	ldc.i.0		0		; i32 0x0
	br.s		$LN3@RecLength
$LN4@RecLength:
	ldloc.0				; $T12623
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	ldc.i.3		3		; i32 0x3
	shl		
$LN3@RecLength:
	call		?getHeaderLength@DataRecord@FJIsam@@$$FSMHXZ
	add		
	ldc.i4.s	12		; i32 0xc
	add		
	ret		
 .end ?RecLength@WDTrans@WDDatas@@$$FU$AAMHXZ		; WDDatas::WDTrans::RecLength
;	.proc.end.i4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?getWordID@WDTrans@WDDatas@@$$FQ$AAMHXZ
.global	?getWordID@WDTrans@WDDatas@@$$FQ$AAMHXZ		; WDDatas::WDTrans::getWordID
?getWordID@WDTrans@WDDatas@@$$FQ$AAMHXZ:		; WDDatas::WDTrans::getWordID
;	.proc.def	D:I()

; Function Header:
; max stack depth = 1
; function size = 7 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)

;	.proc.beg
; Line 309
	ldarg.0				; this$
	ldfld		?WordID@WDTrans@WDDatas@@3HA
	ret		
 .end ?getWordID@WDTrans@WDDatas@@$$FQ$AAMHXZ		; WDDatas::WDTrans::getWordID
;	.proc.end.i4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?getMeanNo@WDTrans@WDDatas@@$$FQ$AAMHXZ
.global	?getMeanNo@WDTrans@WDDatas@@$$FQ$AAMHXZ		; WDDatas::WDTrans::getMeanNo
?getMeanNo@WDTrans@WDDatas@@$$FQ$AAMHXZ:		; WDDatas::WDTrans::getMeanNo
;	.proc.def	D:I()

; Function Header:
; max stack depth = 1
; function size = 7 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)

;	.proc.beg
; Line 315
	ldarg.0				; this$
	ldfld		?MeanNo@WDTrans@WDDatas@@3HA
	ret		
 .end ?getMeanNo@WDTrans@WDDatas@@$$FQ$AAMHXZ		; WDDatas::WDTrans::getMeanNo
;	.proc.end.i4
.global	?ErrorCode2@WDDatasException@WDDatas@@3HA	; WDDatas::WDDatasException::ErrorCode2
.global	?ErrorCode@WDDatasException@WDDatas@@3HA	; WDDatas::WDDatasException::ErrorCode
.global	
.global	
	.bss
.local	$T12635,0
.local	?ErrorCode2@WDDatasException@WDDatas@@3HA,4	; WDDatas::WDDatasException::ErrorCode2
.local	?ErrorCode@WDDatasException@WDDatas@@3HA,4	; WDDatas::WDDatasException::ErrorCode
.local	$StringLiteralTok$??_C@_1CA@KNNNLHNN@0?$KE0?s0?G0?C0?$KP0?$LJc?$AH?$FL?$JK0L?$HL?DV?rY?$BG0g0Y0?$AC?$AA?$AA@,4
.local	,4
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?getTransID@WDTrans@WDDatas@@$$FQ$AAMHH@Z
.global	?getTransID@WDTrans@WDDatas@@$$FQ$AAMHH@Z	; WDDatas::WDTrans::getTransID
?getTransID@WDTrans@WDDatas@@$$FQ$AAMHH@Z:		; WDDatas::WDTrans::getTransID
;	.proc.def	D:I(I)

; Function Header:
; max stack depth = 2
; function size = 71 bytes
; local varsig tk = 0x1100000E 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.i4 1,"inIdx$" SIG: i4
;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.mptr 0,"tmpWDDataException$12249" SIG: class (token:0x4F0E11)
;	.local.u4 1,"$T12632" SIG: genericInst (token:0x100000E) <i4>

;	.proc.beg
; Line 323
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.1				; $T12632
	ldloc.1				; $T12632
	brtrue.s	$LN3@getTransID
	ldc.i.-1	-1		; i32 0xffffffff
	ret		
$LN3@getTransID:
; Line 325
	ldarg.1				; inIdx$
	ldc.i.0		0		; i32 0x0
	blt.s		$LN1@getTransID
	ldarg.1				; inIdx$
	ldloc.1				; $T12632
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	bge.s		$LN1@getTransID
; Line 333
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldarg.1				; inIdx$
	callvirt	?get@default@?$List@H@Generic@Collections@System@@$$FU$AAMHH@Z
	ret		
$LN1@getTransID:
; Line 328
	ldstr		$StringLiteralTok$??_C@_1CA@KNNNLHNN@0?$KE0?s0?G0?C0?$KP0?$LJc?$AH?$FL?$JK0L?$HL?DV?rY?$BG0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.0				; tmpWDDataException$12249
; Line 329
	ldloc.0				; tmpWDDataException$12249
	ldc.i4		10506		; i32 0x290a
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 330
	ldloc.0				; tmpWDDataException$12249
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 331
	ldloc.0				; tmpWDDataException$12249
	throw.u2	
; Line 334
	ldc.i.0		0		; i32 0x0
	ret		
 .end ?getTransID@WDTrans@WDDatas@@$$FQ$AAMHH@Z		; WDDatas::WDTrans::getTransID
;	.proc.end.i4
	.bss
.local	$T12640,0
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?getTransNo@WDTrans@WDDatas@@$$FQ$AAMHH@Z
.global	?getTransNo@WDTrans@WDDatas@@$$FQ$AAMHH@Z	; WDDatas::WDTrans::getTransNo
?getTransNo@WDTrans@WDDatas@@$$FQ$AAMHH@Z:		; WDDatas::WDTrans::getTransNo
;	.proc.def	D:I(I)

; Function Header:
; max stack depth = 2
; function size = 71 bytes
; local varsig tk = 0x1100000E 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.i4 1,"inIdx$" SIG: i4
;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.mptr 0,"tmpWDDataException$12259" SIG: class (token:0x4F0E11)
;	.local.u4 1,"$T12639" SIG: genericInst (token:0x100000E) <i4>

;	.proc.beg
; Line 339
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.1				; $T12639
	ldloc.1				; $T12639
	brtrue.s	$LN3@getTransNo
	ldc.i.-1	-1		; i32 0xffffffff
	ret		
$LN3@getTransNo:
; Line 341
	ldarg.1				; inIdx$
	ldc.i.0		0		; i32 0x0
	blt.s		$LN1@getTransNo
	ldarg.1				; inIdx$
	ldloc.1				; $T12639
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	bge.s		$LN1@getTransNo
; Line 349
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldarg.1				; inIdx$
	callvirt	?get@default@?$List@H@Generic@Collections@System@@$$FU$AAMHH@Z
	ret		
$LN1@getTransNo:
; Line 344
	ldstr		$StringLiteralTok$??_C@_1CA@KNNNLHNN@0?$KE0?s0?G0?C0?$KP0?$LJc?$AH?$FL?$JK0L?$HL?DV?rY?$BG0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.0				; tmpWDDataException$12259
; Line 345
	ldloc.0				; tmpWDDataException$12259
	ldc.i4		10514		; i32 0x2912
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 346
	ldloc.0				; tmpWDDataException$12259
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 347
	ldloc.0				; tmpWDDataException$12259
	throw.u2	
; Line 350
	ldc.i.0		0		; i32 0x0
	ret		
 .end ?getTransNo@WDTrans@WDDatas@@$$FQ$AAMHH@Z		; WDDatas::WDTrans::getTransNo
;	.proc.end.i4
	.bss
.local	$T12644,0
.local	$StringLiteralTok$??_C@_1BG@GAPALFHB@SX?$IK?$JO?$AAI?$AAD0LN?$ANkc0g0Y0?$AC?$AA?$AA@,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?setWordID@WDTrans@WDDatas@@$$FQ$AAMXH@Z
.global	?setWordID@WDTrans@WDDatas@@$$FQ$AAMXH@Z	; WDDatas::WDTrans::setWordID
?setWordID@WDTrans@WDDatas@@$$FQ$AAMXH@Z:		; WDDatas::WDTrans::setWordID
;	.proc.def	D:V(I)

; Function Header:
; max stack depth = 2
; function size = 43 bytes
; local varsig tk = 0x1100000F 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.formal.i4 1,"inData$" SIG: i4
;	.local.mptr 0,"tmpWDDataException$12266" SIG: class (token:0x4F0E11)

;	.proc.beg
; Line 357
	ldarg.1				; inData$
	ldc.i.0		0		; i32 0x0
	bgt.s		$LN1@setWordID
; Line 360
	ldstr		$StringLiteralTok$??_C@_1BG@GAPALFHB@SX?$IK?$JO?$AAI?$AAD0LN?$ANkc0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.0				; tmpWDDataException$12266
; Line 361
	ldloc.0				; tmpWDDataException$12266
	ldc.i4		10507		; i32 0x290b
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 362
	ldloc.0				; tmpWDDataException$12266
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 363
	ldloc.0				; tmpWDDataException$12266
	throw.u2	
$LN1@setWordID:
; Line 366
	ldarg.0				; this$
	ldarg.1				; inData$
	stfld		?WordID@WDTrans@WDDatas@@3HA
; Line 367
	ret		
 .end ?setWordID@WDTrans@WDDatas@@$$FQ$AAMXH@Z		; WDDatas::WDTrans::setWordID
;	.proc.end.void
	.bss
.local	$T12648,0
.local	$StringLiteralTok$??_C@_1BG@FADACBCC@a?$APTs?$AAN?$AAo0LN?$ANkc0g0Y0?$AC?$AA?$AA@,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?setMeanNo@WDTrans@WDDatas@@$$FQ$AAMXH@Z
.global	?setMeanNo@WDTrans@WDDatas@@$$FQ$AAMXH@Z	; WDDatas::WDTrans::setMeanNo
?setMeanNo@WDTrans@WDDatas@@$$FQ$AAMXH@Z:		; WDDatas::WDTrans::setMeanNo
;	.proc.def	D:V(I)

; Function Header:
; max stack depth = 2
; function size = 43 bytes
; local varsig tk = 0x1100000F 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.formal.i4 1,"inData$" SIG: i4
;	.local.mptr 0,"tmpWDDataException$12274" SIG: class (token:0x4F0E11)

;	.proc.beg
; Line 373
	ldarg.1				; inData$
	ldc.i.0		0		; i32 0x0
	bgt.s		$LN1@setMeanNo
; Line 376
	ldstr		$StringLiteralTok$??_C@_1BG@FADACBCC@a?$APTs?$AAN?$AAo0LN?$ANkc0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.0				; tmpWDDataException$12274
; Line 377
	ldloc.0				; tmpWDDataException$12274
	ldc.i4		10508		; i32 0x290c
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 378
	ldloc.0				; tmpWDDataException$12274
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 379
	ldloc.0				; tmpWDDataException$12274
	throw.u2	
$LN1@setMeanNo:
; Line 382
	ldarg.0				; this$
	ldarg.1				; inData$
	stfld		?MeanNo@WDTrans@WDDatas@@3HA
; Line 383
	ret		
 .end ?setMeanNo@WDTrans@WDDatas@@$$FQ$AAMXH@Z		; WDDatas::WDTrans::setMeanNo
;	.proc.end.void
	.bss
.local	$T12653,0
.local	$StringLiteralTok$??_C@_1BG@PJGFPFKC@?$HP?$PL?$IK3?$AAI?$AAD0LN?$ANkc0g0Y0?$AC?$AA?$AA@,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?setTransID@WDTrans@WDDatas@@$$FQ$AAMXHH@Z
.global	?setTransID@WDTrans@WDDatas@@$$FQ$AAMXHH@Z	; WDDatas::WDTrans::setTransID
?setTransID@WDTrans@WDDatas@@$$FQ$AAMXHH@Z:		; WDDatas::WDTrans::setTransID
;	.proc.def	D:V(II)

; Function Header:
; max stack depth = 3
; function size = 105 bytes
; local varsig tk = 0x11000010 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.i4 2,"inIdx$" SIG: i4
;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.formal.i4 1,"inData$" SIG: i4
;	.local.mptr 0,"tmpWDDataException$12288" SIG: class (token:0x4F0E11)
;	.local.u4 2,"$T12652" SIG: genericInst (token:0x100000E) <i4>
;	.local.mptr 1,"tmpWDDataException$12283" SIG: class (token:0x4F0E11)

;	.proc.beg
; Line 390
	ldarg.1				; inData$
	ldc.i.0		0		; i32 0x0
	bgt.s		$LN3@setTransID
; Line 393
	ldstr		$StringLiteralTok$??_C@_1BG@PJGFPFKC@?$HP?$PL?$IK3?$AAI?$AAD0LN?$ANkc0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.1				; tmpWDDataException$12283
; Line 394
	ldloc.1				; tmpWDDataException$12283
	ldc.i4		10509		; i32 0x290d
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 395
	ldloc.1				; tmpWDDataException$12283
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 396
	ldloc.1				; tmpWDDataException$12283
	throw.u2	
$LN3@setTransID:
; Line 400
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.2				; $T12652
	ldloc.2				; $T12652
	brfalse.s	$LN1@setTransID
	ldarg.2				; inIdx$
	ldc.i.0		0		; i32 0x0
	blt.s		$LN1@setTransID
	ldarg.2				; inIdx$
	ldloc.2				; $T12652
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	bge.s		$LN1@setTransID
; Line 410
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldarg.2				; inIdx$
	ldarg.1				; inData$
	callvirt	?set@default@?$List@H@Generic@Collections@System@@$$FU$AAMXHH@Z
	br.s		$LN4@setTransID
$LN1@setTransID:
; Line 403
	ldstr		$StringLiteralTok$??_C@_1CA@KNNNLHNN@0?$KE0?s0?G0?C0?$KP0?$LJc?$AH?$FL?$JK0L?$HL?DV?rY?$BG0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.0				; tmpWDDataException$12288
; Line 404
	ldloc.0				; tmpWDDataException$12288
	ldc.i4		10509		; i32 0x290d
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 405
	ldloc.0				; tmpWDDataException$12288
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 406
	ldloc.0				; tmpWDDataException$12288
	throw.u2	
$LN4@setTransID:
; Line 411
	ret		
 .end ?setTransID@WDTrans@WDDatas@@$$FQ$AAMXHH@Z	; WDDatas::WDTrans::setTransID
;	.proc.end.void
	.bss
.local	$T12658,0
.local	$StringLiteralTok$??_C@_1BK@MNEELNMN@?$HP?$PL?$IK3a?$APTs?$AAN?$AAo0LN?$ANkc0g0Y0?$AC?$AA?$AA@,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?setTransNo@WDTrans@WDDatas@@$$FQ$AAMXHH@Z
.global	?setTransNo@WDTrans@WDDatas@@$$FQ$AAMXHH@Z	; WDDatas::WDTrans::setTransNo
?setTransNo@WDTrans@WDDatas@@$$FQ$AAMXHH@Z:		; WDDatas::WDTrans::setTransNo
;	.proc.def	D:V(II)

; Function Header:
; max stack depth = 3
; function size = 105 bytes
; local varsig tk = 0x11000010 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.i4 2,"inIdx$" SIG: i4
;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.formal.i4 1,"inData$" SIG: i4
;	.local.mptr 0,"tmpWDDataException$12301" SIG: class (token:0x4F0E11)
;	.local.u4 2,"$T12657" SIG: genericInst (token:0x100000E) <i4>
;	.local.mptr 1,"tmpWDDataException$12296" SIG: class (token:0x4F0E11)

;	.proc.beg
; Line 417
	ldarg.1				; inData$
	ldc.i.0		0		; i32 0x0
	bgt.s		$LN3@setTransNo
; Line 420
	ldstr		$StringLiteralTok$??_C@_1BK@MNEELNMN@?$HP?$PL?$IK3a?$APTs?$AAN?$AAo0LN?$ANkc0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.1				; tmpWDDataException$12296
; Line 421
	ldloc.1				; tmpWDDataException$12296
	ldc.i4		10515		; i32 0x2913
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 422
	ldloc.1				; tmpWDDataException$12296
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 423
	ldloc.1				; tmpWDDataException$12296
	throw.u2	
$LN3@setTransNo:
; Line 427
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.2				; $T12657
	ldloc.2				; $T12657
	brfalse.s	$LN1@setTransNo
	ldarg.2				; inIdx$
	ldc.i.0		0		; i32 0x0
	blt.s		$LN1@setTransNo
	ldarg.2				; inIdx$
	ldloc.2				; $T12657
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	bge.s		$LN1@setTransNo
; Line 437
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldarg.2				; inIdx$
	ldarg.1				; inData$
	callvirt	?set@default@?$List@H@Generic@Collections@System@@$$FU$AAMXHH@Z
	br.s		$LN4@setTransNo
$LN1@setTransNo:
; Line 430
	ldstr		$StringLiteralTok$??_C@_1CA@KNNNLHNN@0?$KE0?s0?G0?C0?$KP0?$LJc?$AH?$FL?$JK0L?$HL?DV?rY?$BG0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.0				; tmpWDDataException$12301
; Line 431
	ldloc.0				; tmpWDDataException$12301
	ldc.i4		10515		; i32 0x2913
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 432
	ldloc.0				; tmpWDDataException$12301
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 433
	ldloc.0				; tmpWDDataException$12301
	throw.u2	
$LN4@setTransNo:
; Line 438
	ret		
 .end ?setTransNo@WDTrans@WDDatas@@$$FQ$AAMXHH@Z	; WDDatas::WDTrans::setTransNo
;	.proc.end.void
	.bss
.local	$T12662,0
.local	$StringLiteralTok$??_C@_1BI@HAMBLEJO@?$HP?$PL?$IK3?$GA?EX10LN?$ANetT?$AI0g0Y0?$AC?$AA?$AA@,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?AddTransID@WDTrans@WDDatas@@$$FQ$AAMXHH@Z
.global	?AddTransID@WDTrans@WDDatas@@$$FQ$AAMXHH@Z	; WDDatas::WDTrans::AddTransID
?AddTransID@WDTrans@WDDatas@@$$FQ$AAMXHH@Z:		; WDDatas::WDTrans::AddTransID
;	.proc.def	D:V(II)

; Function Header:
; max stack depth = 2
; function size = 188 bytes
; local varsig tk = 0x11000011 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.formal.i4 2,"inNo$" SIG: i4
;	.formal.i4 1,"inID$" SIG: i4
;	.local.mptr 0,"tmpWDDataException$12321" SIG: class (token:0x4F0E11)
;	.local.mptr 1,"tmpWDDataException$12312" SIG: class (token:0x4F0E11)
;	.local.mptr 2,"tmpWDDataException$12309" SIG: class (token:0x4F0E11)

;	.proc.beg
; Line 444
	ldarg.1				; inID$
	ldc.i.0		0		; i32 0x0
	bgt.s		$LN5@AddTransID
; Line 447
	ldstr		$StringLiteralTok$??_C@_1BG@PJGFPFKC@?$HP?$PL?$IK3?$AAI?$AAD0LN?$ANkc0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.2				; tmpWDDataException$12309
; Line 448
	ldloc.2				; tmpWDDataException$12309
	ldc.i4		10510		; i32 0x290e
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 449
	ldloc.2				; tmpWDDataException$12309
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 450
	ldloc.2				; tmpWDDataException$12309
	throw.u2	
$LN5@AddTransID:
; Line 453
	ldarg.2				; inNo$
	ldc.i.0		0		; i32 0x0
	bgt.s		$LN4@AddTransID
; Line 456
	ldstr		$StringLiteralTok$??_C@_1BK@MNEELNMN@?$HP?$PL?$IK3a?$APTs?$AAN?$AAo0LN?$ANkc0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.1				; tmpWDDataException$12312
; Line 457
	ldloc.1				; tmpWDDataException$12312
	ldc.i4		10510		; i32 0x290e
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 458
	ldloc.1				; tmpWDDataException$12312
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 459
	ldloc.1				; tmpWDDataException$12312
	throw.u2	
$LN4@AddTransID:
; Line 463
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	brtrue.s	$LN3@AddTransID
; Line 465
	ldarg.0				; this$
	newobj		??0?$List@H@Generic@Collections@System@@$$FQ$AAM@XZ
	stfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
$LN3@AddTransID:
; Line 467
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldarg.1				; inID$
	callvirt	?Add@?$List@H@Generic@Collections@System@@$$FU$AAMXH@Z
; Line 469
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	brtrue.s	$LN2@AddTransID
; Line 471
	ldarg.0				; this$
	newobj		??0?$List@H@Generic@Collections@System@@$$FQ$AAM@XZ
	stfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
$LN2@AddTransID:
; Line 473
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldarg.2				; inNo$
	callvirt	?Add@?$List@H@Generic@Collections@System@@$$FU$AAMXH@Z
; Line 476
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	beq.s		$LN1@AddTransID
; Line 479
	ldstr		$StringLiteralTok$??_C@_1BI@HAMBLEJO@?$HP?$PL?$IK3?$GA?EX10LN?$ANetT?$AI0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.0				; tmpWDDataException$12321
; Line 480
	ldloc.0				; tmpWDDataException$12321
	ldc.i4		10510		; i32 0x290e
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 481
	ldloc.0				; tmpWDDataException$12321
	ldc.i.3		3		; i32 0x3
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 482
	ldloc.0				; tmpWDDataException$12321
	throw.u2	
$LN1@AddTransID:
; Line 486
	ret		
 .end ?AddTransID@WDTrans@WDDatas@@$$FQ$AAMXHH@Z	; WDDatas::WDTrans::AddTransID
;	.proc.end.void
	.bss
.local	$T12667,0
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?RemoveTransID@WDTrans@WDDatas@@$$FQ$AAMXH@Z
.global	?RemoveTransID@WDTrans@WDDatas@@$$FQ$AAMXH@Z	; WDDatas::WDTrans::RemoveTransID
?RemoveTransID@WDTrans@WDDatas@@$$FQ$AAMXH@Z:		; WDDatas::WDTrans::RemoveTransID
;	.proc.def	D:V(I)

; Function Header:
; max stack depth = 2
; function size = 136 bytes
; local varsig tk = 0x11000010 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.i4 1,"inIdx$" SIG: i4
;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.mptr 0,"tmpWDDataException$12330" SIG: class (token:0x4F0E11)
;	.local.mptr 1,"tmpWDDataException$12333" SIG: class (token:0x4F0E11)
;	.local.u4 2,"$T12666" SIG: genericInst (token:0x100000E) <i4>

;	.proc.beg
; Line 493
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.2				; $T12666
	ldloc.2				; $T12666
	brfalse.s	$LN2@RemoveTran
	ldarg.1				; inIdx$
	ldc.i.0		0		; i32 0x0
	blt.s		$LN2@RemoveTran
	ldarg.1				; inIdx$
	ldloc.2				; $T12666
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	bge.s		$LN2@RemoveTran
; Line 503
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	beq.s		$LN1@RemoveTran
; Line 506
	ldstr		$StringLiteralTok$??_C@_1BI@HAMBLEJO@?$HP?$PL?$IK3?$GA?EX10LN?$ANetT?$AI0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.1				; tmpWDDataException$12333
; Line 507
	ldloc.1				; tmpWDDataException$12333
	ldc.i4		10511		; i32 0x290f
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 508
	ldloc.1				; tmpWDDataException$12333
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 509
	ldloc.1				; tmpWDDataException$12333
	throw.u2	
$LN1@RemoveTran:
; Line 512
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldarg.1				; inIdx$
	callvirt	?RemoveAt@?$List@H@Generic@Collections@System@@$$FU$AAMXH@Z
; Line 513
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldarg.1				; inIdx$
	callvirt	?RemoveAt@?$List@H@Generic@Collections@System@@$$FU$AAMXH@Z
	br.s		$LN4@RemoveTran
$LN2@RemoveTran:
; Line 496
	ldstr		$StringLiteralTok$??_C@_1CA@KNNNLHNN@0?$KE0?s0?G0?C0?$KP0?$LJc?$AH?$FL?$JK0L?$HL?DV?rY?$BG0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.0				; tmpWDDataException$12330
; Line 497
	ldloc.0				; tmpWDDataException$12330
	ldc.i4		10511		; i32 0x290f
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 498
	ldloc.0				; tmpWDDataException$12330
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 499
	ldloc.0				; tmpWDDataException$12330
	throw.u2	
$LN4@RemoveTran:
; Line 515
	ret		
 .end ?RemoveTransID@WDTrans@WDDatas@@$$FQ$AAMXH@Z	; WDDatas::WDTrans::RemoveTransID
;	.proc.end.void
	.bss
.local	$T12671,0
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?CountTransID@WDTrans@WDDatas@@$$FQ$AAMHXZ
.global	?CountTransID@WDTrans@WDDatas@@$$FQ$AAMHXZ	; WDDatas::WDTrans::CountTransID
?CountTransID@WDTrans@WDDatas@@$$FQ$AAMHXZ:		; WDDatas::WDTrans::CountTransID
;	.proc.def	D:I()

; Function Header:
; max stack depth = 1
; function size = 19 bytes
; local varsig tk = 0x1100000B 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.u4 0,"$T12670" SIG: genericInst (token:0x100000E) <i4>

;	.proc.beg
; Line 520
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.0				; $T12670
	ldloc.0				; $T12670
	brtrue.s	$LN2@CountTrans
; Line 522
	ldc.i.0		0		; i32 0x0
	ret		
$LN2@CountTrans:
; Line 524
	ldloc.0				; $T12670
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	ret		
 .end ?CountTransID@WDTrans@WDDatas@@$$FQ$AAMHXZ	; WDDatas::WDTrans::CountTransID
;	.proc.end.i4
.global	
.global	
	.bss
.local	$T12696,0
.local	$StringLiteralTok$??_C@_1CA@PDKIJOOO@0?G0?$PM0?$LP0n0?$LD0?T0?$PM0kY1eW0W0?$HO0W0_0?$AC?$AA?$AA@,4
.local	$TypeTok$110DD6FC$,4
.local	$StringLiteralTok$??_C@_1CA@DCBKAEPK@0?$LD0?T0?$PMQH0?G0?$PM0?$LP?$JFw0Lw?m0Y0N0?$HO0Y0?$AC?$AA?$AA@,4
.local	,4
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?getData@WDTrans@WDDatas@@$$FA$AAMP$01AEP$01AE@Z
.global	?getData@WDTrans@WDDatas@@$$FA$AAMP$01AEP$01AE@Z ; WDDatas::WDTrans::getData
?getData@WDTrans@WDDatas@@$$FA$AAMP$01AEP$01AE@Z:	; WDDatas::WDTrans::getData
;	.proc.def	D:P(P)

; Function Header:
; max stack depth = 4
; function size = 259 bytes
; local varsig tk = 0x11000014 
; Exception Information:
; 1 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.formal.mptr 1,"inData$" SIG: szarray (token:0x4F2685)
;	.local.mptr 3,"tmpWDDataException$12434" SIG: class (token:0x4F0E11)
;	.local.mptr 7,"exp$12433" SIG: class (token:0x4F0D85)
;	.local.i4 2,"i$12429" SIG: i4
;	.local.i4 0,"tmpPos$" SIG: i4
;	.local.mptr 4,"tmpWDDataException$12351" SIG: class (token:0x4F0E11)
;	.local.i4 5,"tmpTransIDSize$12683" SIG: i4
;	.local.u4 6,"$T12692" SIG: genericInst (token:0x100000E) <i4>
;	.local.mptr 1,"rtData$" SIG: szarray (token:0x4F2685)

;	.proc.beg
; Line 533
	ldnull		0		; i32 0x0
	stloc.1				; rtData$
; Line 539
	ldarg.1				; inData$
	brfalse.s	$LN7@getData
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.s		6		; $T12692
	ldloc.s		6		; $T12692
	brtrue.s	$LN17@getData
	ldc.i.0		0		; i32 0x0
	stloc.s		5		; tmpTransIDSize$12683
	br.s		$LN16@getData
$LN17@getData:
	ldloc.s		6		; $T12692
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	ldc.i.3		3		; i32 0x3
	shl		
	stloc.s		5		; tmpTransIDSize$12683
$LN16@getData:
	ldarg.1				; inData$
	ldlen		
	ldloc.s		5		; tmpTransIDSize$12683
	ldc.i4.s	12		; i32 0xc
	add		
	bge.s		$LN7@getData
; Line 542
	ldstr		$StringLiteralTok$??_C@_1CA@DCBKAEPK@0?$LD0?T0?$PMQH0?G0?$PM0?$LP?$JFw0Lw?m0Y0N0?$HO0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.s		4		; tmpWDDataException$12351
; Line 543
	ldloc.s		4		; tmpWDDataException$12351
	ldc.i4		10512		; i32 0x2910
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 544
	ldloc.s		4		; tmpWDDataException$12351
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 545
	ldloc.s		4		; tmpWDDataException$12351
	throw.u2	
$LN7@getData:
	nop		
$LN24@getData:
; Line 551
	ldarg.1				; inData$
	brtrue.s	$LN5@getData
; Line 553
	ldarg.0				; this$
	call		?DataLength@WDTrans@WDDatas@@$$FQ$AAMHXZ
	newarr		$TypeTok$110DD6FC$
	stloc.1				; rtData$
; Line 554
	br.s		$LN4@getData
$LN5@getData:
; Line 555
	ldarg.1				; inData$
	stloc.1				; rtData$
$LN4@getData:
; Line 558
	ldc.i.0		0		; i32 0x0
	stloc.0				; tmpPos$
; Line 560
	ldarg.0				; this$
	ldfld		?WordID@WDTrans@WDDatas@@3HA
	ldloc.1				; rtData$
	ldc.i.0		0		; i32 0x0
	call		?Int32ToArray@FJIFuncs@FJIsam@@$$FSMP$01AEHP$01AEH@Z
	pop		
; Line 561
	ldc.i.4		4		; i32 0x4
	stloc.0				; tmpPos$
; Line 563
	ldarg.0				; this$
	ldfld		?MeanNo@WDTrans@WDDatas@@3HA
	ldloc.1				; rtData$
	ldc.i.4		4		; i32 0x4
	call		?Int32ToArray@FJIFuncs@FJIsam@@$$FSMP$01AEHP$01AEH@Z
	pop		
; Line 564
	ldc.i.8		8		; i32 0x8
	stloc.0				; tmpPos$
; Line 566
	ldarg.0				; this$
	call		?CountTransID@WDTrans@WDDatas@@$$FQ$AAMHXZ
	ldloc.1				; rtData$
	ldc.i.8		8		; i32 0x8
	call		?Int32ToArray@FJIFuncs@FJIsam@@$$FSMP$01AEHP$01AEH@Z
	pop		
; Line 567
	ldc.i4.s	12		; i32 0xc
	stloc.0				; tmpPos$
; Line 569
	ldc.i.0		0		; i32 0x0
	stloc.2				; i$12429
$LL3@getData:
	ldloc.2				; i$12429
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	callvirt	?get@Count@?$List@H@Generic@Collections@System@@$$FU$AAMHXZ
	bge.s		$LN1@getData
; Line 571
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldloc.2				; i$12429
	callvirt	?get@default@?$List@H@Generic@Collections@System@@$$FU$AAMHH@Z
	ldloc.1				; rtData$
	ldloc.0				; tmpPos$
	call		?Int32ToArray@FJIFuncs@FJIsam@@$$FSMP$01AEHP$01AEH@Z
	pop		
; Line 572
	ldloc.0				; tmpPos$
	ldc.i.4		4		; i32 0x4
	add		
	stloc.0				; tmpPos$
; Line 574
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldloc.2				; i$12429
	callvirt	?get@default@?$List@H@Generic@Collections@System@@$$FU$AAMHH@Z
	ldloc.1				; rtData$
	ldloc.0				; tmpPos$
	call		?Int32ToArray@FJIFuncs@FJIsam@@$$FSMP$01AEHP$01AEH@Z
	pop		
; Line 575
	ldloc.0				; tmpPos$
	ldc.i.4		4		; i32 0x4
	add		
	stloc.0				; tmpPos$
; Line 569
	ldloc.2				; i$12429
	ldc.i.1		1		; i32 0x1
	add		
	stloc.2				; i$12429
	br.s		$LL3@getData
$LN1@getData:
; Line 576
	leave.s		$LN10@getData
__catch$?getData@WDTrans@WDDatas@@$$FA$AAMP$01AEP$01AE@Z$0:
; Line 578
	imp.push	
	stloc.s		7		; exp$12433
; Line 580
	ldstr		$StringLiteralTok$??_C@_1CA@PDKIJOOO@0?G0?$PM0?$LP0n0?$LD0?T0?$PM0kY1eW0W0?$HO0W0_0?$AC?$AA?$AA@
	ldloc.s		7		; exp$12433
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.3				; tmpWDDataException$12434
; Line 581
	ldloc.3				; tmpWDDataException$12434
	ldc.i4		10512		; i32 0x2910
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 582
	ldloc.3				; tmpWDDataException$12434
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 583
	ldloc.3				; tmpWDDataException$12434
	throw.u2	
$LN15@getData:
	leave.s		$LN10@getData
$LN10@getData:
; Line 587
	ldloc.1				; rtData$
	ret		
 .end ?getData@WDTrans@WDDatas@@$$FA$AAMP$01AEP$01AE@Z	; WDDatas::WDTrans::getData
;	.proc.end.mptr
	.bss
.local	$T12715,0
.local	$StringLiteralTok$??_C@_1CG@BHOEGJEO@0?$LD0?T0?$PMQC0?G0?$PM0?$LP?$JFw0Lkc0W0O0B0?$IK0?$HO0?$FL0?$JD0?$AC?$AA?$AA@,4
.local	$StringLiteralTok$??_C@_1BO@MACLDLLC@0?$LD0?T0?$PMQC0?G0?$PM0?$LP0Lg?$CK?$IK?9?$FL?$JK0g0Y0?$AC?$AA?$AA@,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?setData@WDTrans@WDDatas@@$$FA$AAMXP$01AE@Z
.global	?setData@WDTrans@WDDatas@@$$FA$AAMXP$01AE@Z	; WDDatas::WDTrans::setData
?setData@WDTrans@WDDatas@@$$FA$AAMXP$01AE@Z:		; WDDatas::WDTrans::setData
;	.proc.def	D:V(P)

; Function Header:
; max stack depth = 4
; function size = 345 bytes
; local varsig tk = 0x11000015 
; Exception Information:
; 1 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.formal.mptr 1,"inData$" SIG: szarray (token:0x4F2685)
;	.local.mptr 1,"tmpWDDataException$12475" SIG: class (token:0x4F0E11)
;	.local.mptr 10,"exp$12474" SIG: class (token:0x4F0D85)
;	.local.i4 11,"tmpTransNo$12473" SIG: i4
;	.local.i4 12,"tmpTransID$12472" SIG: i4
;	.local.i4 2,"i$12468" SIG: i4
;	.local.mptr 3,"tmpWDDataException$12466" SIG: class (token:0x4F0E11)
;	.local.u4 6,"$T12713" SIG: genericInst (token:0x100000E) <i4>
;	.local.u4 7,"$T12712" SIG: genericInst (token:0x100000E) <i4>
;	.local.i4 8,"tmpTransIDCnt$" SIG: i4
;	.local.i4 0,"tmpPos$" SIG: i4
;	.local.mptr 4,"tmpWDDataException$12452" SIG: class (token:0x4F0E11)
;	.local.mptr 5,"tmpWDDataException$12445" SIG: class (token:0x4F0E11)

;	.proc.beg
; Line 597
	ldarg.1				; inData$
	brtrue.s	$LN11@setData
; Line 600
	ldstr		$StringLiteralTok$??_C@_1BO@MACLDLLC@0?$LD0?T0?$PMQC0?G0?$PM0?$LP0Lg?$CK?$IK?9?$FL?$JK0g0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.s		5		; tmpWDDataException$12445
; Line 601
	ldloc.s		5		; tmpWDDataException$12445
	ldc.i4		10513		; i32 0x2911
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 602
	ldloc.s		5		; tmpWDDataException$12445
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 603
	ldloc.s		5		; tmpWDDataException$12445
	throw.u2	
$LN11@setData:
; Line 606
	ldarg.1				; inData$
	ldlen		
	stloc.s		9		
	ldloc.s		9		
	ldc.i4.s	12		; u32 0xc
	bge.un.s	$LN10@setData
	ldloc.s		9		
	ldc.i.3		3		; u32 0x3
	and		
	brfalse.s	$LN10@setData
; Line 609
	ldstr		$StringLiteralTok$??_C@_1CG@BHOEGJEO@0?$LD0?T0?$PMQC0?G0?$PM0?$LP?$JFw0Lkc0W0O0B0?$IK0?$HO0?$FL0?$JD0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.s		4		; tmpWDDataException$12452
; Line 610
	ldloc.s		4		; tmpWDDataException$12452
	ldc.i4		10513		; i32 0x2911
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 611
	ldloc.s		4		; tmpWDDataException$12452
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 612
	ldloc.s		4		; tmpWDDataException$12452
	throw.u2	
$LN10@setData:
	nop		
$LN24@setData:
; Line 618
	ldc.i.0		0		; i32 0x0
	stloc.0				; tmpPos$
; Line 620
	ldarg.0				; this$
	ldarg.1				; inData$
	ldc.i.0		0		; i32 0x0
	call		?ArrayToInt32@FJIFuncs@FJIsam@@$$FSMHP$01AEH@Z
	stfld		?WordID@WDTrans@WDDatas@@3HA
; Line 621
	ldc.i.4		4		; i32 0x4
	stloc.0				; tmpPos$
; Line 623
	ldarg.0				; this$
	ldarg.1				; inData$
	ldc.i.4		4		; i32 0x4
	call		?ArrayToInt32@FJIFuncs@FJIsam@@$$FSMHP$01AEH@Z
	stfld		?MeanNo@WDTrans@WDDatas@@3HA
; Line 624
	ldc.i.8		8		; i32 0x8
	stloc.0				; tmpPos$
; Line 626
	ldarg.1				; inData$
	ldc.i.8		8		; i32 0x8
	call		?ArrayToInt32@FJIFuncs@FJIsam@@$$FSMHP$01AEH@Z
	stloc.s		8		; tmpTransIDCnt$
; Line 627
	ldc.i4.s	12		; i32 0xc
	stloc.0				; tmpPos$
; Line 629
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.s		7		; $T12712
	ldloc.s		7		; $T12712
	brtrue.s	$LN8@setData
; Line 631
	ldarg.0				; this$
	newobj		??0?$List@H@Generic@Collections@System@@$$FQ$AAM@XZ
	stfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
; Line 632
	br.s		$LN7@setData
$LN8@setData:
; Line 633
	ldloc.s		7		; $T12712
	callvirt	?Clear@?$List@H@Generic@Collections@System@@$$FU$AAMXXZ
$LN7@setData:
; Line 636
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	stloc.s		6		; $T12713
	ldloc.s		6		; $T12713
	brtrue.s	$LN6@setData
; Line 638
	ldarg.0				; this$
	newobj		??0?$List@H@Generic@Collections@System@@$$FQ$AAM@XZ
	stfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
; Line 639
	br.s		$LN5@setData
$LN6@setData:
; Line 640
	ldloc.s		6		; $T12713
	callvirt	?Clear@?$List@H@Generic@Collections@System@@$$FU$AAMXXZ
$LN5@setData:
; Line 645
	ldarg.1				; inData$
	ldlen		
	ldloc.s		8		; tmpTransIDCnt$
	ldc.i.8		8		; u32 0x8
	mul		
	ldc.i4.s	12		; u32 0xc
	add		
	beq.s		$LN4@setData
; Line 648
	ldstr		$StringLiteralTok$??_C@_1CG@BHOEGJEO@0?$LD0?T0?$PMQC0?G0?$PM0?$LP?$JFw0Lkc0W0O0B0?$IK0?$HO0?$FL0?$JD0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.3				; tmpWDDataException$12466
; Line 649
	ldloc.3				; tmpWDDataException$12466
	ldc.i4		10513		; i32 0x2911
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 650
	ldloc.3				; tmpWDDataException$12466
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 651
	ldloc.3				; tmpWDDataException$12466
	throw.u2	
$LN4@setData:
; Line 655
	ldc.i.0		0		; i32 0x0
	stloc.2				; i$12468
$LL3@setData:
	ldloc.2				; i$12468
	ldloc.s		8		; tmpTransIDCnt$
	bge.s		$LN1@setData
; Line 660
	ldarg.1				; inData$
	ldloc.0				; tmpPos$
	call		?ArrayToInt32@FJIFuncs@FJIsam@@$$FSMHP$01AEH@Z
	stloc.s		12		; tmpTransID$12472
; Line 661
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldloc.s		12		; tmpTransID$12472
	callvirt	?Add@?$List@H@Generic@Collections@System@@$$FU$AAMXH@Z
; Line 662
	ldloc.0				; tmpPos$
	ldc.i.4		4		; i32 0x4
	add		
	stloc.0				; tmpPos$
; Line 664
	ldarg.1				; inData$
	ldloc.0				; tmpPos$
	call		?ArrayToInt32@FJIFuncs@FJIsam@@$$FSMHP$01AEH@Z
	stloc.s		11		; tmpTransNo$12473
; Line 665
	ldarg.0				; this$
	ldfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	ldloc.s		11		; tmpTransNo$12473
	callvirt	?Add@?$List@H@Generic@Collections@System@@$$FU$AAMXH@Z
; Line 666
	ldloc.0				; tmpPos$
	ldc.i.4		4		; i32 0x4
	add		
	stloc.0				; tmpPos$
; Line 655
	ldloc.2				; i$12468
	ldc.i.1		1		; i32 0x1
	add		
	stloc.2				; i$12468
	br.s		$LL3@setData
$LN1@setData:
; Line 668
	leave.s		$LN14@setData
__catch$?setData@WDTrans@WDDatas@@$$FA$AAMXP$01AE@Z$0:
; Line 670
	imp.push	
	stloc.s		10		; exp$12474
; Line 672
	ldstr		$StringLiteralTok$??_C@_1CA@PDKIJOOO@0?G0?$PM0?$LP0n0?$LD0?T0?$PM0kY1eW0W0?$HO0W0_0?$AC?$AA?$AA@
	ldloc.s		10		; exp$12474
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.1				; tmpWDDataException$12475
; Line 673
	ldloc.1				; tmpWDDataException$12475
	ldc.i4		10513		; i32 0x2911
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 674
	ldloc.1				; tmpWDDataException$12475
	ldc.i.3		3		; i32 0x3
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 675
	ldloc.1				; tmpWDDataException$12475
	throw.u2	
$LN19@setData:
	leave.s		$LN14@setData
$LN14@setData:
$LN23@setData:
; Line 677
	ret		
 .end ?setData@WDTrans@WDDatas@@$$FA$AAMXP$01AE@Z	; WDDatas::WDTrans::setData
;	.proc.end.void
; Function compile flags: /Ogtp
	.text
	.comdat	any, ?<Dispose>@WDRec@WDDatas@@$$FU$AAMXXZ
.global	?<Dispose>@WDRec@WDDatas@@$$FU$AAMXXZ		; WDDatas::WDRec::<Dispose>
?<Dispose>@WDRec@WDDatas@@$$FU$AAMXXZ:			; WDDatas::WDRec::<Dispose>
;	.proc.def	D:V()

; Function Header:
; max stack depth = 2
; function size = 14 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED7E9).class (token:0x4ED7EB)

;	.proc.beg
	ldarg.0				; this$
	ldc.i.1		1		; u8 0x1
	callvirt	?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
	ldarg.0				; this$
	call		?SuppressFinalize@GC@System@@$$FSMXP$AAVObject@2@@Z
	ret		
 .end ?<Dispose>@WDRec@WDDatas@@$$FU$AAMXXZ		; WDDatas::WDRec::<Dispose>
;	.proc.end.void
; Function compile flags: /Ogtp
	.text
	.comdat	any, ?<Dispose>@WDTrans@WDDatas@@$$FM$AAMX_N@Z
.global	?<Dispose>@WDTrans@WDDatas@@$$FM$AAMX_N@Z	; WDDatas::WDTrans::<Dispose>
?<Dispose>@WDTrans@WDDatas@@$$FM$AAMX_N@Z:		; WDDatas::WDTrans::<Dispose>
;	.proc.def	D:V(I)

; Function Header:
; max stack depth = 2
; function size = 27 bytes
; local varsig tk = 0x0 
; Exception Information:
; 1 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.formal.u1 1,"disposing$" SIG: bool

;	.proc.beg
	ldarg.1				; disposing$
	brfalse.s	$LN3@
$LN13@:
	ldarg.0				; this$
	call		??1WDTrans@WDDatas@@$$FA$AAM@XZ
$LN2@:
	leave.s		$LN12@
$LN7@:
	ldarg.0				; this$
	ldc.i.1		1		; u8 0x1
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN9@:
	endfinally	
$LN3@:
	ldarg.0				; this$
	ldc.i.0		0		; u8 0x0
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
$LN12@:
	ret		
 .end ?<Dispose>@WDTrans@WDDatas@@$$FM$AAMX_N@Z		; WDDatas::WDTrans::<Dispose>
;	.proc.end.void
.global	
	.bss
.local	$T12752,0
.local	$StringLiteralTok$??_C@_1CM@IBIPDKIN@0?G0?$PM0?$LP0?l0?$LD0?$PM0?IS?V_?$JH0g0?$KI0?i0?$PM0Lvzu?$BP0W0?$HO0W0_0?$AC?$AA?$AA@,4
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?getRecord@WDTrans@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
.global	?getRecord@WDTrans@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ ; WDDatas::WDTrans::getRecord
?getRecord@WDTrans@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ: ; WDDatas::WDTrans::getRecord
;	.proc.def	D:P()

; Function Header:
; max stack depth = 4
; function size = 153 bytes
; local varsig tk = 0x11000017 
; Exception Information:
; 2 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.mptr 1,"tmpWDDataException$11989" SIG: class (token:0x4F0E11)
;	.local.mptr 4,"exp$11988" SIG: class (token:0x4F0D85)
;	.local.mptr 2,"tmpWDDataException$11983" SIG: class (token:0x4F0E11)
;	.local.mptr 5,"exp$11982" SIG: class (token:0x4F0D85)
;	.local.mptr 3,"tmpDat$" SIG: szarray (token:0x4F2685)
;	.local.mptr 0,"tmpRec$" SIG: class (token:0x4F0EA5)

;	.proc.beg
; Line 85
	ldnull		0		; i32 0x0
	stloc.0				; tmpRec$
; Line 89
	ldarg.0				; this$
	call		?getRecord@WDRec@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	brtrue.s	$LN4@getRecord
$LN23@getRecord:
; Line 93
	ldarg.0				; this$
	ldnull		0		; i32 0x0
	call		?getData@WDTrans@WDDatas@@$$FA$AAMP$01AEP$01AE@Z
	stloc.3				; tmpDat$
; Line 94
	newobj		??0DataRecord@FJIsam@@$$FQ$AAM@XZ
	stloc.0				; tmpRec$
; Line 95
	ldloc.0				; tmpRec$
	ldloc.3				; tmpDat$
	ldarg.0				; this$
	call		?DataLength@WDTrans@WDDatas@@$$FQ$AAMHXZ
	call		?setData@DataRecord@FJIsam@@$$FQ$AAMXP$01AEH@Z
; Line 96
	ldarg.0				; this$
	ldloc.0				; tmpRec$
	call		?setRecord@WDRec@WDDatas@@$$FU$AAMXP$AAVDataRecord@FJIsam@@@Z
	leave.s		$LN9@getRecord
__catch$?getRecord@WDTrans@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ$0:
; Line 97
	imp.push	
	stloc.s		5		; exp$11982
; Line 99
	ldstr		$StringLiteralTok$??_C@_1CM@IBIPDKIN@0?G0?$PM0?$LP0?l0?$LD0?$PM0?IS?V_?$JH0g0?$KI0?i0?$PM0Lvzu?$BP0W0?$HO0W0_0?$AC?$AA?$AA@
	ldloc.s		5		; exp$11982
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.2				; tmpWDDataException$11983
; Line 100
	ldloc.2				; tmpWDDataException$11983
	ldc.i4		10502		; i32 0x2906
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 101
	ldloc.2				; tmpWDDataException$11983
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 102
	ldloc.2				; tmpWDDataException$11983
	throw.u2	
$LN14@getRecord:
	leave.s		$LN9@getRecord
$LN4@getRecord:
	nop		
$LN24@getRecord:
; Line 107
	ldarg.0				; this$
	ldnull		0		; i32 0x0
	call		?getData@WDTrans@WDDatas@@$$FA$AAMP$01AEP$01AE@Z
	stloc.3				; tmpDat$
; Line 108
	ldarg.0				; this$
	call		?getRecord@WDRec@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	stloc.0				; tmpRec$
; Line 109
	ldloc.0				; tmpRec$
	ldloc.3				; tmpDat$
	ldarg.0				; this$
	call		?DataLength@WDTrans@WDDatas@@$$FQ$AAMHXZ
	call		?setData@DataRecord@FJIsam@@$$FQ$AAMXP$01AEH@Z
	leave.s		$LN9@getRecord
__catch$?getRecord@WDTrans@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ$2:
; Line 110
	imp.push	
	stloc.s		4		; exp$11988
; Line 112
	ldstr		$StringLiteralTok$??_C@_1CM@IBIPDKIN@0?G0?$PM0?$LP0?l0?$LD0?$PM0?IS?V_?$JH0g0?$KI0?i0?$PM0Lvzu?$BP0W0?$HO0W0_0?$AC?$AA?$AA@
	ldloc.s		4		; exp$11988
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.1				; tmpWDDataException$11989
; Line 113
	ldloc.1				; tmpWDDataException$11989
	ldc.i4		10502		; i32 0x2906
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 114
	ldloc.1				; tmpWDDataException$11989
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 115
	ldloc.1				; tmpWDDataException$11989
	throw.u2	
$LN18@getRecord:
	leave.s		$LN9@getRecord
$LN9@getRecord:
; Line 122
	ldloc.0				; tmpRec$
	ret		
 .end ?getRecord@WDTrans@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ ; WDDatas::WDTrans::getRecord
;	.proc.end.mptr
	.bss
.local	$T12776,0
.local	$StringLiteralTok$??_C@_1CM@POGCAHHH@0?G0?$PM0?$LP0?l0?$LD0?$PM0?I?$IK?9?$FL?$JK0g0?$KI0?i0?$PM0Lvzu?$BP0W0?$HO0W0_0?$AC?$AA?$AA@,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?setRecord@WDTrans@WDDatas@@$$FU$AAMXP$AAVDataRecord@FJIsam@@@Z
.global	?setRecord@WDTrans@WDDatas@@$$FU$AAMXP$AAVDataRecord@FJIsam@@@Z ; WDDatas::WDTrans::setRecord
?setRecord@WDTrans@WDDatas@@$$FU$AAMXP$AAVDataRecord@FJIsam@@@Z: ; WDDatas::WDTrans::setRecord
;	.proc.def	D:V(P)

; Function Header:
; max stack depth = 4
; function size = 112 bytes
; local varsig tk = 0x11000018 
; Exception Information:
; 2 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.formal.mptr 1,"inRec$" SIG: class (token:0x4F0EA5)
;	.local.mptr 0,"tmpWDDataException$12007" SIG: class (token:0x4F0E11)
;	.local.mptr 3,"exp$12006" SIG: class (token:0x4F0D85)
;	.local.mptr 1,"tmpWDDataException$12001" SIG: class (token:0x4F0E11)
;	.local.mptr 4,"exp$12000" SIG: class (token:0x4F0D85)
;	.local.mptr 2,"tmpDat$11999" SIG: szarray (token:0x4F2685)

;	.proc.beg
; Line 128
	ldarg.1				; inRec$
	brfalse.s	$LN4@setRecord
$LN23@setRecord:
; Line 133
	ldarg.1				; inRec$
	ldnull		0		; i32 0x0
	call		?getData@DataRecord@FJIsam@@$$FQ$AAMP$01AEP$01AE@Z
	stloc.2				; tmpDat$11999
; Line 134
	ldarg.0				; this$
	ldloc.2				; tmpDat$11999
	call		?setData@WDTrans@WDDatas@@$$FA$AAMXP$01AE@Z
; Line 135
	ldnull		0		; i32 0x0
	stloc.2				; tmpDat$11999
; Line 136
	ldarg.0				; this$
	ldarg.1				; inRec$
	call		?setRecord@WDRec@WDDatas@@$$FU$AAMXP$AAVDataRecord@FJIsam@@@Z
	leave.s		$LN9@setRecord
__catch$?setRecord@WDTrans@WDDatas@@$$FU$AAMXP$AAVDataRecord@FJIsam@@@Z$0:
; Line 137
	imp.push	
	stloc.s		4		; exp$12000
; Line 139
	ldstr		$StringLiteralTok$??_C@_1CM@POGCAHHH@0?G0?$PM0?$LP0?l0?$LD0?$PM0?I?$IK?9?$FL?$JK0g0?$KI0?i0?$PM0Lvzu?$BP0W0?$HO0W0_0?$AC?$AA?$AA@
	ldloc.s		4		; exp$12000
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.1				; tmpWDDataException$12001
; Line 140
	ldloc.1				; tmpWDDataException$12001
	ldc.i4		10503		; i32 0x2907
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 141
	ldloc.1				; tmpWDDataException$12001
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 142
	ldloc.1				; tmpWDDataException$12001
	throw.u2	
$LN14@setRecord:
	leave.s		$LN9@setRecord
$LN4@setRecord:
	nop		
$LN24@setRecord:
; Line 147
	ldarg.0				; this$
	ldnull		0		; i32 0x0
	call		?setRecord@WDRec@WDDatas@@$$FU$AAMXP$AAVDataRecord@FJIsam@@@Z
	leave.s		$LN9@setRecord
__catch$?setRecord@WDTrans@WDDatas@@$$FU$AAMXP$AAVDataRecord@FJIsam@@@Z$2:
; Line 148
	imp.push	
	stloc.3				; exp$12006
; Line 150
	ldstr		$StringLiteralTok$??_C@_1CM@POGCAHHH@0?G0?$PM0?$LP0?l0?$LD0?$PM0?I?$IK?9?$FL?$JK0g0?$KI0?i0?$PM0Lvzu?$BP0W0?$HO0W0_0?$AC?$AA?$AA@
	ldloc.3				; exp$12006
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.0				; tmpWDDataException$12007
; Line 151
	ldloc.0				; tmpWDDataException$12007
	ldc.i4		10503		; i32 0x2907
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 152
	ldloc.0				; tmpWDDataException$12007
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 153
	ldloc.0				; tmpWDDataException$12007
	throw.u2	
$LN18@setRecord:
	leave.s		$LN9@setRecord
$LN9@setRecord:
; Line 156
	ret		
 .end ?setRecord@WDTrans@WDDatas@@$$FU$AAMXP$AAVDataRecord@FJIsam@@@Z ; WDDatas::WDTrans::setRecord
;	.proc.end.void
.global	
	.bss
.local	$T12801,0
.local	$StringLiteralTok$??_C@_1CG@PFOLFNFI@0?G0?$PM0?$LP0?l0?$LD0?$PM0?I0nf?x?$IP?$LM0kY1eW0W0?$HO0W0_0?$AC?$AA?$AA@,4
.local	$StringLiteralTok$??_C@_1BM@LAKNIOBD@0?l0?$LD0?$PM0?IRJ?$JGd0o0g0M0?$HO0?$FL0?$JD0?$AC?$AA?$AA@,4
.local	$StringLiteralTok$??_C@_1BO@OEMADJDL@?$AAI?$AAS?$AAA?$AAM0?U0?$KB0?$KE0?k0LN?$ANkc0g0Y0?$AC?$AA?$AA@,4
.local	$TypeTok$11280448$,4
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?Write@WDTrans@WDDatas@@$$FU$AAMXXZ
.global	?Write@WDTrans@WDDatas@@$$FU$AAMXXZ		; WDDatas::WDTrans::Write
?Write@WDTrans@WDDatas@@$$FU$AAMXXZ:			; WDDatas::WDTrans::Write
;	.proc.def	D:V()

; Function Header:
; max stack depth = 4
; function size = 204 bytes
; local varsig tk = 0x1100001A 
; Exception Information:
; 2 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.mptr 1,"tmpWDDataException$12196" SIG: class (token:0x4F0E11)
;	.local.mptr 4,"exp$12195" SIG: class (token:0x4F0D85)
;	.local.mptr 2,"tmpWDDataException$12192" SIG: class (token:0x4F0E11)
;	.local.mptr 3,"tmpWDDataException$12184" SIG: class (token:0x4F0E11)
;	.local.mptr 5,"exp$12183" SIG: class (token:0x4F0D85)
;	.local.mptr 0,"tmpParent$" SIG: class (token:0x4F1D9D)

;	.proc.beg
; Line 160
	ldnull		0		; i32 0x0
	stloc.0				; tmpParent$
; Line 164
	ldarg.0				; this$
	call		?getRecord@WDRec@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	brfalse		$LN13@Write
$LN27@Write:
; Line 172
	ldarg.0				; this$
	call		?getRecord@WDRec@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	call		?getParentFile@DataRecord@FJIsam@@$$FQ$AAMP$AAVObject@System@@XZ
	castClass	$TypeTok$11280448$
	stloc.0				; tmpParent$
; Line 173
	ldloc.0				; tmpParent$
	brtrue.s	$LN6@Write
; Line 175
	leave		$LN13@Write
$LN6@Write:
	leave.s		$LN11@Write
__catch$?Write@WDTrans@WDDatas@@$$FU$AAMXXZ$0:
; Line 177
	imp.push	
	stloc.s		5		; exp$12183
; Line 179
	ldstr		$StringLiteralTok$??_C@_1BO@OEMADJDL@?$AAI?$AAS?$AAA?$AAM0?U0?$KB0?$KE0?k0LN?$ANkc0g0Y0?$AC?$AA?$AA@
	ldloc.s		5		; exp$12183
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.3				; tmpWDDataException$12184
; Line 180
	ldloc.3				; tmpWDDataException$12184
	ldc.i4		10504		; i32 0x2908
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 181
	ldloc.3				; tmpWDDataException$12184
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 182
	ldloc.3				; tmpWDDataException$12184
	throw.u2	
$LN18@Write:
	leave.s		$LN11@Write
$LN11@Write:
	nop		
$LN28@Write:
; Line 188
	ldarg.0				; this$
	call		?getRecord@WDRec@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	call		?getRecStat@DataRecord@FJIsam@@$$FQ$AAM?AW4DataRecStat_EN@2@XZ
	brtrue.s	$LN4@Write
; Line 190
	ldloc.0				; tmpParent$
	ldarg.0				; this$
	callvirt	?getRecord@WDTrans@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	call		?AddRecord@FIsam@FJIsam@@$$FQ$AAMXP$AAVDataRecord@2@@Z
	br.s		$LN1@Write
$LN4@Write:
; Line 191
	ldarg.0				; this$
	call		?getRecord@WDRec@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	call		?getRecStat@DataRecord@FJIsam@@$$FQ$AAM?AW4DataRecStat_EN@2@XZ
	ldc.i.1		1		; i32 0x1
	bne.un.s	$LN2@Write
; Line 192
	ldloc.0				; tmpParent$
	ldarg.0				; this$
	callvirt	?getRecord@WDTrans@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	call		?UpdateRecord@FIsam@FJIsam@@$$FQ$AAMXP$AAVDataRecord@2@@Z
$LN1@Write:
; Line 198
	leave.s		$LN13@Write
$LN2@Write:
; Line 195
	ldstr		$StringLiteralTok$??_C@_1BM@LAKNIOBD@0?l0?$LD0?$PM0?IRJ?$JGd0o0g0M0?$HO0?$FL0?$JD0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.2				; tmpWDDataException$12192
; Line 196
	ldloc.2				; tmpWDDataException$12192
	ldc.i4		10504		; i32 0x2908
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 197
	ldloc.2				; tmpWDDataException$12192
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 198
	ldloc.2				; tmpWDDataException$12192
	throw.u2	
$LN19@Write:
; Line 200
	leave.s		$LN13@Write
__catch$?Write@WDTrans@WDDatas@@$$FU$AAMXXZ$2:
	imp.push	
	stloc.s		4		; exp$12195
; Line 202
	ldstr		$StringLiteralTok$??_C@_1CG@PFOLFNFI@0?G0?$PM0?$LP0?l0?$LD0?$PM0?I0nf?x?$IP?$LM0kY1eW0W0?$HO0W0_0?$AC?$AA?$AA@
	ldloc.s		4		; exp$12195
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.1				; tmpWDDataException$12196
; Line 203
	ldloc.1				; tmpWDDataException$12196
	ldc.i4		10504		; i32 0x2908
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 204
	ldloc.1				; tmpWDDataException$12196
	ldc.i.3		3		; i32 0x3
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 205
	ldloc.1				; tmpWDDataException$12196
	throw.u2	
$LN22@Write:
	leave.s		$LN13@Write
$LN13@Write:
; Line 207
	ret		
 .end ?Write@WDTrans@WDDatas@@$$FU$AAMXXZ		; WDDatas::WDTrans::Write
;	.proc.end.void
	.bss
.local	$T12825,0
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ?Delete@WDTrans@WDDatas@@$$FU$AAMXXZ
.global	?Delete@WDTrans@WDDatas@@$$FU$AAMXXZ		; WDDatas::WDTrans::Delete
?Delete@WDTrans@WDDatas@@$$FU$AAMXXZ:			; WDDatas::WDTrans::Delete
;	.proc.def	D:V()

; Function Header:
; max stack depth = 4
; function size = 268 bytes
; local varsig tk = 0x1100001B 
; Exception Information:
; 2 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.mptr 0,"tmpWDDataException$12220" SIG: class (token:0x4F0E11)
;	.local.mptr 4,"exp$12219" SIG: class (token:0x4F0D85)
;	.local.mptr 1,"tmpWDDataException$12217" SIG: class (token:0x4F0E11)
;	.local.mptr 2,"tmpWDDataException$12210" SIG: class (token:0x4F0E11)
;	.local.mptr 5,"exp$12209" SIG: class (token:0x4F0D85)
;	.local.mptr 3,"tmpParent$" SIG: class (token:0x4F1D9D)

;	.proc.beg
; Line 211
	ldnull		0		; i32 0x0
	stloc.3				; tmpParent$
; Line 215
	ldarg.0				; this$
	call		?getRecord@WDRec@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	brtrue.s	$LN8@Delete
; Line 218
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?WordID@WDTrans@WDDatas@@3HA
; Line 219
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?MeanNo@WDTrans@WDDatas@@3HA
; Line 220
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	callvirt	?Clear@?$List@H@Generic@Collections@System@@$$FU$AAMXXZ
; Line 222
	br		$LN9@Delete
$LN8@Delete:
	nop		
$LN27@Delete:
; Line 228
	ldarg.0				; this$
	call		?getRecord@WDRec@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	call		?getParentFile@DataRecord@FJIsam@@$$FQ$AAMP$AAVObject@System@@XZ
	castClass	$TypeTok$11280448$
	stloc.3				; tmpParent$
; Line 229
	ldloc.3				; tmpParent$
	brtrue.s	$LN6@Delete
; Line 232
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?WordID@WDTrans@WDDatas@@3HA
; Line 233
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?MeanNo@WDTrans@WDDatas@@3HA
; Line 234
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	callvirt	?Clear@?$List@H@Generic@Collections@System@@$$FU$AAMXXZ
; Line 236
	leave		$LN9@Delete
$LN6@Delete:
	leave.s		$LN11@Delete
__catch$?Delete@WDTrans@WDDatas@@$$FU$AAMXXZ$0:
; Line 238
	imp.push	
	stloc.s		5		; exp$12209
; Line 240
	ldstr		$StringLiteralTok$??_C@_1BO@OEMADJDL@?$AAI?$AAS?$AAA?$AAM0?U0?$KB0?$KE0?k0LN?$ANkc0g0Y0?$AC?$AA?$AA@
	ldloc.s		5		; exp$12209
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.2				; tmpWDDataException$12210
; Line 241
	ldloc.2				; tmpWDDataException$12210
	ldc.i4		10505		; i32 0x2909
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 242
	ldloc.2				; tmpWDDataException$12210
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 243
	ldloc.2				; tmpWDDataException$12210
	throw.u2	
$LN18@Delete:
	leave.s		$LN11@Delete
$LN11@Delete:
	nop		
$LN28@Delete:
; Line 249
	ldarg.0				; this$
	call		?getRecord@WDRec@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	call		?getRecStat@DataRecord@FJIsam@@$$FQ$AAM?AW4DataRecStat_EN@2@XZ
	brfalse.s	$LN1@Delete
; Line 252
	ldarg.0				; this$
	call		?getRecord@WDRec@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	call		?getRecStat@DataRecord@FJIsam@@$$FQ$AAM?AW4DataRecStat_EN@2@XZ
	ldc.i.1		1		; i32 0x1
	bne.un.s	$LN2@Delete
; Line 253
	ldloc.3				; tmpParent$
	ldarg.0				; this$
	callvirt	?getRecord@WDTrans@WDDatas@@$$FU$AAMP$AAVDataRecord@FJIsam@@XZ
	call		?DeleteRecord@FIsam@FJIsam@@$$FQ$AAMXP$AAVDataRecord@2@@Z
$LN1@Delete:
; Line 259
	leave.s		$LN13@Delete
$LN2@Delete:
; Line 256
	ldstr		$StringLiteralTok$??_C@_1BM@LAKNIOBD@0?l0?$LD0?$PM0?IRJ?$JGd0o0g0M0?$HO0?$FL0?$JD0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.1				; tmpWDDataException$12217
; Line 257
	ldloc.1				; tmpWDDataException$12217
	ldc.i4		10505		; i32 0x2909
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 258
	ldloc.1				; tmpWDDataException$12217
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 259
	ldloc.1				; tmpWDDataException$12217
	throw.u2	
$LN19@Delete:
; Line 261
	leave.s		$LN13@Delete
__catch$?Delete@WDTrans@WDDatas@@$$FU$AAMXXZ$2:
	imp.push	
	stloc.s		4		; exp$12219
; Line 263
	ldstr		$StringLiteralTok$??_C@_1CG@PFOLFNFI@0?G0?$PM0?$LP0?l0?$LD0?$PM0?I0nf?x?$IP?$LM0kY1eW0W0?$HO0W0_0?$AC?$AA?$AA@
	ldloc.s		4		; exp$12219
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.0				; tmpWDDataException$12220
; Line 264
	ldloc.0				; tmpWDDataException$12220
	ldc.i4		10505		; i32 0x2909
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 265
	ldloc.0				; tmpWDDataException$12220
	ldc.i.3		3		; i32 0x3
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 266
	ldloc.0				; tmpWDDataException$12220
	throw.u2	
$LN22@Delete:
	leave.s		$LN13@Delete
$LN13@Delete:
; Line 270
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?WordID@WDTrans@WDDatas@@3HA
; Line 271
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?MeanNo@WDTrans@WDDatas@@3HA
; Line 272
	ldarg.0				; this$
	ldfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
	callvirt	?Clear@?$List@H@Generic@Collections@System@@$$FU$AAMXXZ
$LN9@Delete:
; Line 274
	ret		
 .end ?Delete@WDTrans@WDDatas@@$$FU$AAMXXZ		; WDDatas::WDTrans::Delete
;	.proc.end.void
	.bss
.local	$T12849,0
.local	$StringLiteralTok$??_C@_1CE@JDMCCNFK@0?G0?$PM0?$LP?$IK?9?$FL?$JK0g0?$KI0?i0?$PM0Lvzu?$BP0W0?$HO0W0_0?$AC?$AA?$AA@,4
.local	$StringLiteralTok$??_C@_1CG@NEHHHDPO@0?G0?$PM0?$LP0?l0?$LD0?$PM0?I0n0?G0?$PM0?$LP0Lw?m0Y0N0?$HO0Y0?$AC?$AA?$AA@,4
; Function compile flags: /Ogtp
	.text
	.comdat	noduplicate, ??0WDTrans@WDDatas@@$$FQ$AAM@P$AAVDataRecord@FJIsam@@@Z
.global	??0WDTrans@WDDatas@@$$FQ$AAM@P$AAVDataRecord@FJIsam@@@Z ; WDDatas::WDTrans::WDTrans
??0WDTrans@WDDatas@@$$FQ$AAM@P$AAVDataRecord@FJIsam@@@Z: ; WDDatas::WDTrans::WDTrans
;	.proc.def	D:V(P)

; Function Header:
; max stack depth = 4
; function size = 144 bytes
; local varsig tk = 0x1100001C 
; Exception Information:
; 2 handlers, each consisting of filtered handlers

;	.formal.mptr 1,"inRec$" SIG: class (token:0x4F0EA5)
;	.formal.mptr 0,"this$" SIG: Optional C Binding Modifier(token:0x4ED045).class (token:0x4ED047)
;	.local.mptr 0,"tmpWDDataException$11953" SIG: class (token:0x4F0E11)
;	.local.mptr 2,"exp$11951" SIG: class (token:0x4F0D85)
;	.local.mptr 1,"tmpWDDataException$11420" SIG: class (token:0x4F0E11)

;	.proc.beg
; Line 35
	ldarg.0				; this$
	call		??0Object@System@@$$FQ$AAM@XZ
$LN18@WDTrans@3:
; Line 38
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?WordID@WDTrans@WDDatas@@3HA
; Line 39
	ldarg.0				; this$
	ldc.i.0		0		; i32 0x0
	stfld		?MeanNo@WDTrans@WDDatas@@3HA
; Line 40
	ldarg.0				; this$
	newobj		??0?$List@H@Generic@Collections@System@@$$FQ$AAM@XZ
	stfld		?TransID@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
; Line 41
	ldarg.0				; this$
	newobj		??0?$List@H@Generic@Collections@System@@$$FQ$AAM@XZ
	stfld		?TransNo@WDTrans@WDDatas@@3P$AAV?$List@H@Generic@Collections@System@@$AA
; Line 43
	ldarg.1				; inRec$
	brfalse.s	$LN6@WDTrans@3
; Line 50
	ldarg.1				; inRec$
	call		?getDataLength@DataRecord@FJIsam@@$$FQ$AAMHXZ
	ldc.i4.s	12		; i32 0xc
	blt.s		$LN22@WDTrans@3
	leave.s		$LN2@WDTrans@3
$LN22@WDTrans@3:
; Line 53
	ldstr		$StringLiteralTok$??_C@_1CG@NEHHHDPO@0?G0?$PM0?$LP0?l0?$LD0?$PM0?I0n0?G0?$PM0?$LP0Lw?m0Y0N0?$HO0Y0?$AC?$AA?$AA@
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@@Z
	stloc.1				; tmpWDDataException$11420
; Line 54
	ldloc.1				; tmpWDDataException$11420
	ldc.i4		10501		; i32 0x2905
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 55
	ldloc.1				; tmpWDDataException$11420
	ldc.i.1		1		; i32 0x1
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 56
	ldloc.1				; tmpWDDataException$11420
	throw.u2	
$LN2@WDTrans@3:
; File c:\users\amotoo\documents\myproject\worddicbt\wddatas\wddatas.h
	nop		
$LN19@WDTrans@3:
; File c:\users\amotoo\documents\myproject\worddicbt\wddatas\wdtrans.cpp
; Line 62
	ldarg.0				; this$
	ldarg.1				; inRec$
	callvirt	?setRecord@WDTrans@WDDatas@@$$FU$AAMXP$AAVDataRecord@FJIsam@@@Z
	leave.s		$LN6@WDTrans@3
__catch$??0WDTrans@WDDatas@@$$FQ$AAM@P$AAVDataRecord@FJIsam@@@Z$0:
; Line 63
	imp.push	
	stloc.2				; exp$11951
; Line 65
	ldstr		$StringLiteralTok$??_C@_1CE@JDMCCNFK@0?G0?$PM0?$LP?$IK?9?$FL?$JK0g0?$KI0?i0?$PM0Lvzu?$BP0W0?$HO0W0_0?$AC?$AA?$AA@
	ldloc.2				; exp$11951
	newobj		??0WDDatasException@WDDatas@@$$FQ$AAM@P$AAVString@System@@P$AAVException@3@@Z
	stloc.0				; tmpWDDataException$11953
; Line 66
	ldloc.0				; tmpWDDataException$11953
	ldc.i4		10501		; i32 0x2905
	stfld		?ErrorCode@WDDatasException@WDDatas@@3HA
; Line 67
	ldloc.0				; tmpWDDataException$11953
	ldc.i.2		2		; i32 0x2
	stfld		?ErrorCode2@WDDatasException@WDDatas@@3HA
; Line 68
	ldloc.0				; tmpWDDataException$11953
	throw.u2	
$LN12@WDTrans@3:
	leave.s		$LN6@WDTrans@3
$LN6@WDTrans@3:
$LN5@WDTrans@3:
$LN17@WDTrans@3:
; Line 70
	leave.s		$LN20@WDTrans@3
$LN21@WDTrans@3:
	ldarg.0				; this$
	ldc.i.1		1		; u8 0x1
	call		?<Dispose>@WDRec@WDDatas@@$$FM$AAMX_N@Z
	endfinally	
$LN20@WDTrans@3:
; Line 50
	ret		
 .end ??0WDTrans@WDDatas@@$$FQ$AAM@P$AAVDataRecord@FJIsam@@@Z ; WDDatas::WDTrans::WDTrans
;	.proc.end.void
